import type { TopicCategory } from "@/features/practice/types";

export const TOPIC_CATEGORIES: TopicCategory[] = [
  {
    id: "profile",
    label: "프로필/배경",
    description: "서베이 기본 정보",
    topics: [
      { id: "job-business", title: "사업/회사 운영", english: "Business Owner" },
      { id: "job-remote", title: "재택근무/재택 사업", english: "Work from Home" },
      { id: "job-teacher", title: "교사/교육자", english: "Teacher/Educator" },
      { id: "job-none", title: "일 경험 없음", english: "No Work Experience" },
      { id: "student-yes", title: "학생", english: "Student (Yes)" },
      { id: "student-no", title: "비학생", english: "Student (No)" },
      { id: "course-degree", title: "학위 과정 수업", english: "Degree Course" },
      { id: "course-vocab", title: "어휘 수업", english: "Vocabulary Class" },
      { id: "course-skill", title: "전문 기술 향상", english: "Professional Skills" },
      { id: "course-5y", title: "수강 후 5년 이상", english: "5+ Years Since Course" },
      { id: "residence-alone", title: "혼자 거주", english: "Live Alone" },
      { id: "residence-roommate", title: "룸메이트와 거주", english: "Live with Roommate" },
      { id: "residence-family", title: "가족과 거주", english: "Live with Family" },
      { id: "residence-dorm", title: "기숙사 거주", english: "Dormitory" },
      { id: "residence-military", title: "군대 막사 거주", english: "Military Barracks" },
    ],
  },
  {
    id: "leisure",
    label: "여가/일상",
    description: "취미와 일상 활동",
    topics: [
      {
        id: "music",
        title: "음악 감상",
        english: "Music",
        badges: [
          { label: "일반 빈출", count: 17 },
          { label: "어드밴스", count: 7 },
        ],
      },
      {
        id: "house",
        title: "집",
        english: "House",
        badges: [
          { label: "일반 빈출", count: 14 },
          { label: "어드밴스", count: 4 },
        ],
      },
      {
        id: "vacation-home",
        title: "집에서 보내는 휴가",
        english: "Vacation at Home",
        badges: [{ label: "일반 빈출", count: 8 }],
      },
      {
        id: "overseas-trip",
        title: "해외 여행",
        english: "Overseas Trip",
        badges: [
          { label: "일반 빈출", count: 6 },
          { label: "롤플레이", count: 5 },
          { label: "어드밴스", count: 1 },
        ],
      },
      {
        id: "park",
        title: "공원 가기",
        english: "Park",
        badges: [
          { label: "일반 빈출", count: 6 },
          { label: "어드밴스", count: 1 },
        ],
      },
      {
        id: "movie",
        title: "영화 감상",
        english: "Movie",
        badges: [
          { label: "일반 빈출", count: 4 },
          { label: "롤플레이", count: 2 },
          { label: "어드밴스", count: 2 },
        ],
      },
      {
        id: "shopping",
        title: "쇼핑하기",
        english: "Shopping",
        badges: [
          { label: "일반 빈출", count: 2 },
          { label: "어드밴스", count: 1 },
        ],
      },
      {
        id: "domestic-trip",
        title: "국내 여행",
        english: "Domestic Trip",
        badges: [
          { label: "일반 빈출", count: 1 },
          { label: "롤플레이", count: 5 },
        ],
      },
      { id: "jogging", title: "조깅", english: "Jogging", badges: [{ label: "일반", count: 1 }] },
      { id: "walking", title: "걷기", english: "Walking", badges: [{ label: "일반", count: 0 }] },
      { id: "no-exercise", title: "운동을 전혀 하지 않음", english: "No Exercise", badges: [{ label: "일반", count: 0 }] },
      { id: "performance", title: "공연 관람", english: "Performance", badges: [{ label: "롤플레이", count: 1 }] },
      { id: "concert", title: "콘서트 관람", english: "Concert" },
      { id: "game", title: "게임하기", english: "Gaming" },
      { id: "texting", title: "친구들과 문자 대화", english: "Texting" },
      { id: "news", title: "뉴스 보거나 듣기", english: "News" },
      { id: "club", title: "클럽/나이트 가기", english: "Club", badges: [{ label: "어드밴스", count: 1 }] },
      { id: "reality-show", title: "리얼리티 쇼", english: "Reality Show" },
      { id: "exam-prep", title: "시험 대비 과정 수강", english: "Exam Prep" },
      { id: "museum", title: "박물관 관람", english: "Museum" },
      { id: "sns-post", title: "SNS에 글 쓰기", english: "SNS Posting" },
      { id: "drive", title: "차 드라이브", english: "Driving" },
      { id: "camping", title: "캠핑", english: "Camping", badges: [{ label: "롤플레이", count: 1 }] },
      { id: "tv", title: "TV 시청", english: "TV Watching" },
      { id: "volunteer", title: "자원봉사", english: "Volunteering" },
      { id: "sports-watch", title: "스포츠 관람", english: "Sports Watching" },
      { id: "job-search", title: "구직 활동", english: "Job Search" },
      { id: "beach", title: "해변에 가기", english: "Beach" },
      { id: "home-improve", title: "주거 개선 활동", english: "Home Improvement" },
      { id: "pub-bar", title: "술집/바", english: "Pub/Bar", badges: [{ label: "어드밴스", count: 1 }] },
      { id: "chess", title: "체스", english: "Chess" },
      { id: "cooking-show", title: "요리 프로그램 시청", english: "Cooking Show" },
      { id: "billiards", title: "당구", english: "Billiards" },
      { id: "cafe", title: "카페", english: "Cafe", badges: [{ label: "어드밴스", count: 1 }] },
    ],
  },
  {
    id: "hobby",
    label: "취미/관심사",
    description: "개인 취미 중심",
    topics: [
      { id: "read-to-kids", title: "아이에게 책 읽어 주기", english: "Reading to Kids" },
      { id: "instrument", title: "악기 연주", english: "Musical Instrument", badges: [{ label: "롤플레이", count: 2 }] },
      { id: "reading", title: "독서", english: "Reading", badges: [{ label: "어드밴스", count: 1 }] },
      { id: "photo", title: "사진 촬영", english: "Photography" },
      { id: "writing", title: "글쓰기", english: "Writing" },
      { id: "cooking", title: "요리", english: "Cooking" },
      { id: "newspaper", title: "신문 읽기", english: "Reading Newspaper" },
      { id: "pet", title: "애완동물 기르기", english: "Pet" },
      { id: "drawing", title: "그림 그리기", english: "Drawing" },
      { id: "singing", title: "노래/합창", english: "Singing" },
      { id: "dancing", title: "춤추기", english: "Dancing" },
      { id: "stock", title: "주식 투자", english: "Stock Investment" },
      { id: "travel-blogs", title: "여행 잡지/블로그", english: "Travel Blogs" },
    ],
  },
  {
    id: "sports",
    label: "운동/건강",
    description: "운동 관련 경험",
    topics: [
      { id: "gym", title: "헬스/헬스장", english: "Health/Gym", badges: [{ label: "롤플레이", count: 3 }] },
      { id: "soccer", title: "축구", english: "Soccer", badges: [{ label: "롤플레이", count: 1 }] },
      { id: "hiking", title: "하이킹/트레킹", english: "Hiking", badges: [{ label: "롤플레이", count: 1 }, { label: "어드밴스", count: 1 }] },
      { id: "golf", title: "골프", english: "Golf", badges: [{ label: "어드밴스", count: 1 }] },
      { id: "basketball", title: "농구", english: "Basketball" },
      { id: "volleyball", title: "배구", english: "Volleyball" },
      { id: "ice-skating", title: "아이스 스케이트", english: "Ice Skating" },
      { id: "taekwondo", title: "태권도", english: "Taekwondo" },
      { id: "ski", title: "스키/스노보드", english: "Ski/Snowboard" },
      { id: "baseball", title: "야구/소프트볼", english: "Baseball" },
      { id: "tennis", title: "테니스", english: "Tennis" },
      { id: "training", title: "운동 수업/레슨", english: "Training Class" },
      { id: "croquet", title: "크로켓", english: "Croquet" },
      { id: "cycling", title: "자전거", english: "Cycling" },
      { id: "fishing", title: "낚시", english: "Fishing" },
      { id: "badminton", title: "배드민턴", english: "Badminton" },
      { id: "hockey", title: "하키", english: "Hockey" },
      { id: "swimming", title: "수영", english: "Swimming" },
      { id: "football", title: "미식축구", english: "American Football" },
      { id: "table-tennis", title: "탁구", english: "Table Tennis" },
      { id: "yoga", title: "요가", english: "Yoga" },
    ],
  },
  {
    id: "travel",
    label: "여행/출장",
    description: "이동과 휴가 경험",
    topics: [
      { id: "business-domestic", title: "국내 출장", english: "Domestic Business Trip" },
      { id: "business-overseas", title: "해외 출장", english: "Overseas Business Trip" },
      { id: "trip-domestic", title: "국내 여행", english: "Domestic Trip", badges: [{ label: "롤플레이", count: 5 }] },
      { id: "trip-overseas", title: "해외 여행", english: "Overseas Trip", badges: [{ label: "롤플레이", count: 5 }, { label: "일반 빈출", count: 6 }] },
    ],
  },
  {
    id: "unexpected",
    label: "돌발/상황 대처",
    description: "돌발 주제 빈출",
    topics: [
      { id: "recycling", title: "재활용", english: "Recycling", badges: [{ label: "돌발", count: 8 }] },
      { id: "appointment", title: "예약/약속", english: "Appointment", badges: [{ label: "돌발", count: 5 }] },
      { id: "bank", title: "은행", english: "Bank", badges: [{ label: "돌발", count: 4 }] },
      { id: "cellphone", title: "휴대폰", english: "Cellphone", badges: [{ label: "돌발", count: 4 }] },
      { id: "geography", title: "지형", english: "Geography", badges: [{ label: "돌발", count: 4 }] },
      { id: "gathering", title: "모임/기념일", english: "Gathering", badges: [{ label: "돌발", count: 3 }] },
      { id: "restaurant", title: "식당", english: "Restaurant", badges: [{ label: "돌발", count: 3 }] },
      { id: "technology", title: "기술", english: "Technology", badges: [{ label: "돌발", count: 3 }] },
      { id: "weather", title: "날씨", english: "Weather", badges: [{ label: "돌발", count: 3 }] },
      { id: "holidays", title: "휴일", english: "Holidays", badges: [{ label: "돌발", count: 3 }] },
      { id: "furniture", title: "가구", english: "Furniture", badges: [{ label: "돌발", count: 2 }] },
      { id: "internet", title: "인터넷", english: "Internet", badges: [{ label: "돌발", count: 2 }] },
      { id: "electronics", title: "전자제품", english: "Electronics", badges: [{ label: "돌발", count: 2 }] },
      { id: "housework", title: "집안일", english: "House Work", badges: [{ label: "돌발", count: 2 }] },
      { id: "industry", title: "산업", english: "Industry", badges: [{ label: "돌발", count: 2 }] },
      { id: "dentist", title: "치과", english: "Dentist", badges: [{ label: "돌발", count: 1 }] },
      { id: "family-friends", title: "가족/친구", english: "Family/Friends", badges: [{ label: "돌발", count: 1 }, { label: "롤플레이", count: 5 }] },
      { id: "haircut", title: "미용실", english: "Hair-cut", badges: [{ label: "돌발", count: 1 }] },
      { id: "hotel", title: "호텔", english: "Hotel", badges: [{ label: "돌발", count: 1 }] },
      { id: "transport", title: "대중교통", english: "Transportation", badges: [{ label: "돌발", count: 1 }] },
      { id: "celebrity", title: "연예인", english: "Celebrity", badges: [{ label: "롤플레이", count: 2 }] },
      { id: "mp3", title: "MP3", english: "MP3", badges: [{ label: "롤플레이", count: 1 }] },
      { id: "computer", title: "컴퓨터", english: "Computer", badges: [{ label: "롤플레이", count: 1 }] },
      { id: "party", title: "파티", english: "Party", badges: [{ label: "롤플레이", count: 1 }] },
    ],
  },
];
